### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by rabernat** [intake/filesystem_spec#427]
This error just showed up in one of our CI environments in which fsspec is installed via pip. It's currently causing https://github.com/MITgcm/xmitgcm/pull/225 to fail.

The [environment](https://github.com/MITgcm/xmitgcm/blob/master/ci/environment-py36-xarraymaster.yml) looks like this
```yaml
name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - dask
  - numpy
  - pytest
  - future
  - zarr
  - cftime
  - pip:
    - cachetools
    - git+https://github.com/pydata/xarray.git
    - fsspec
    - codecov
    - pytest-cov
```

The code calls
```
from fsspec.implementations.http import HTTPFileSystem
```

and we get
```
    from __future__ import print_function, division, absolute_import
    
>   import aiohttp
E   ModuleNotFoundError: No module named 'aiohttp'
```

https://travis-ci.org/github/MITgcm/xmitgcm/jobs/731092719
